use_frameworks!
#source 'https://github.com/VE66/CCConfigSetting.git'
#source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'CCNetworking_Example' do
  pod 'CCNetworking', :path => '../'
  pod 'CCConfigSetting', :git=> 'https://github.com/VE66/CCConfigSetting.git'
  target 'CCNetworking_Tests' do
    inherit! :search_paths

    
  end
end
